#pragma once
enum tnumber { TEOF, TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE, TCHAR, TFLOAT, TEQUAL, TNOTEQU, TLESSE, TGREATE, TAND, TOR, TINC, TDEC, TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN, TLPAREN, TRPAREN, TLBRACE, TRBRACE, TASSIGN, TFLOATNUM, TSTAR, TPLUS, TMOD, TMINUS, TSLASH, TINTNUM, TIDENT, TCHARCONST, TNUMBER, TSEMI, TDOT, TSTRING, TERROR };
