#pragma once
enum tnumber { TEOF, TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE, TCHAR, TFLOAT, TEQUAL, TNOTEQU, TLESSE, TGREATE, TAND, TOR, TINC, TDEC, TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN, TLPAREN, TRPAREN, TLBRACE, TRBRACE,TIDENT, TNUMBER, TSEMI, TSTRING };
